# Generated by Django 4.2.3 on 2023-08-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftlyapp', '0002_category_parent_order_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
